version: '3.0'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
  chat:
    build: .
    env_file:
      - .env
    ports:
      - '8080:8080'
    command: go run main.go
    depends_on:
      - postgres
